

export const ADD_TRANSACTION = 'ADD_TRANSACTION';
export const ADD_BUDGET_ITEM = 'ADD_BUDGET_ITEM';

export const REMOVE_TRANSACTION = 'REMOVE_TRANSACTION';
export const REMOVE_BUDGET_ITEM = 'REMOVE_BUDGET_ITEM';

export const FETCHING_BUDGET_REQUEST = 'FETCHING_BUDGET_REQUEST';
export const FETCHING_BUDGET_SUCCESS = 'FETCHING_BUDGET_SUCCESS';
export const FETCHING_BUDGET_FAILURE = 'FETCHING_BUDGET_FAILURE';

export const FETCHING_TRANSACTION_REQUEST = 'FETCHING_TRANSACTION_REQUEST';
export const FETCHING_TRANSACTION_SUCCESS = 'FETCHING_TRANSACTION_SUCCESS';
export const FETCHING_TRANSACTION_FAILURE = 'FETCHING_TRANSACTION_FAILURE';

export const CREATE_USER_REQUESTED = 'CREATE_USER_REQUESTED';
export const CREATE_USER_SUCCESS = 'CREATE_USER_SUCCESS';
export const CREATE_USER_FAIL= 'CREATE_USER_FAIL';

export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_FAIL ='LOGIN_USER_FAIL';
